ALTER TYPE "MfaMethod" ADD VALUE IF NOT EXISTS 'EMAIL';
ALTER TYPE "MfaChallengePurpose" ADD VALUE IF NOT EXISTS 'PHONE_RECOVERY_EMAIL';
ALTER TYPE "MfaChallengePurpose" ADD VALUE IF NOT EXISTS 'PHONE_RECOVERY_SMS';
